---
env:
  global:
    - CC_TEST_REPORTER_ID=84bb987517388fd3f106f685b088598f34db2dced78783e4c12963f1a475f3ae
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
before_install: gem install bundler -v 2.0.2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
